Repository polkadot-evm/frontier, pull requests merged in 2022-05, with the labels that each got.

#643 Add clippy support
  .github/workflows/rust.yml
  client/consensus/src/lib.rs
  client/db/src/lib.rs
  client/db/src/utils.rs
  client/mapping-sync/src/lib.rs
  client/mapping-sync/src/worker.rs
  client/rpc-core/src/types/block_number.rs
  client/rpc-core/src/types/bytes.rs
  client/rpc-core/src/types/filter.rs
  client/rpc-core/src/types/pubsub.rs
  client/rpc-core/src/types/transaction_request.rs
  client/rpc/Cargo.toml
  client/rpc/src/eth/block.rs
  client/rpc/src/eth/cache/lru_cache.rs
  client/rpc/src/eth/cache/mod.rs
  client/rpc/src/eth/client.rs
  client/rpc/src/eth/execute.rs
  client/rpc/src/eth/fee.rs
  client/rpc/src/eth/filter.rs
  client/rpc/src/eth/mod.rs
  client/rpc/src/eth/state.rs
  client/rpc/src/eth/submit.rs
  client/rpc/src/eth/transaction.rs
  client/rpc/src/eth_pubsub.rs
  client/rpc/src/lib.rs
  client/rpc/src/overrides/mod.rs
  client/rpc/src/signer.rs
  frame/base-fee/src/lib.rs
  frame/dynamic-fee/src/lib.rs
  frame/ethereum/src/lib.rs
  frame/evm/precompile/blake2/src/lib.rs
  frame/evm/precompile/curve25519/src/lib.rs
  frame/evm/precompile/dispatch/src/lib.rs
  frame/evm/precompile/modexp/src/lib.rs
  frame/evm/src/lib.rs
  frame/evm/src/runner/stack.rs
  frame/evm/test-vector-support/src/lib.rs
  primitives/consensus/src/lib.rs
  primitives/rpc/src/lib.rs
  primitives/self-contained/src/checked_extrinsic.rs
  primitives/storage/src/lib.rs
  template/node/src/command_helper.rs
  template/node/src/main.rs
  template/node/src/rpc.rs
  template/node/src/service.rs
  template/runtime/src/lib.rs
  template/runtime/src/precompiles.rs
Labels: A4-needsresolving

#637 Add extrinsic weight and lenght check
  client/rpc/src/eth/cache/mod.rs
  frame/base-fee/src/lib.rs
  frame/ethereum/src/lib.rs
  frame/ethereum/src/mock.rs
  frame/ethereum/src/tests/eip1559.rs
  frame/ethereum/src/tests/eip2930.rs
  frame/ethereum/src/tests/legacy.rs
  frame/ethereum/src/tests/mod.rs
  primitives/self-contained/src/checked_extrinsic.rs
  primitives/self-contained/src/lib.rs
  template/examples/contract-erc20/create-erc20-rpc.ts
  template/examples/contract-erc20/create-erc20.ts
  template/examples/contract-hello/index.js
  template/runtime/src/lib.rs
  ts-tests/tests/test-block.ts
  ts-tests/tests/test-contract-methods.ts
  ts-tests/tests/test-gas.ts
  ts-tests/tests/util.ts
Labels: A7-gotissues

#391 Update header size field
  client/rpc/src/eth_pubsub.rs
Labels: A0-pleasereview
